[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
dashmap = "5.5.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio-util = { version = "0.7.9", features = ["codec"]}
